### ISSUE TITLE
Cannot read properties of undefined (reading 'settings')

### ISSUE THREAD

**Issue by soareseneves** [wbraganca/yii2-dynamicform#333]
I'm getting this error in console after page is loaded. How can I solve this?

```
Uncaught TypeError: Cannot read properties of undefined (reading 'settings')
    at _parseTemplate (yii2-dynamic-form.js:90:48)
    at HTMLFormElement.<anonymous> (yii2-dynamic-form.js:37:42)
    at Function.each (jquery.js:385:19)
    at jQuery.fn.init.each (jquery.js:207:17)
    at jQuery.fn.init.init (yii2-dynamic-form.js:36:25)
    at $.fn.yiiDynamicForm (yii2-dynamic-form.js:19:33)
    at 137:2686:26
    at dispatch (jquery.js:5466:27)
    at elemData.handle (jquery.js:5270:28)
```

I'm using https://github.com/kartik-v/yii2-widget-activeform instead of Yii's default activeform

**Comment by soareseneves** [comment]
This fixes my issue: https://github.com/wbraganca/yii2-dynamicform/issues/224#issuecomment-355312744
I wonder why this hasn't been fixed, I will create a PR.
